ProductSelectionWebApp/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProductSelectionWebApp.Areas.Admin.ViewModel;
using ProductSelectionWebApp.Data;
using ProductSelectionWebApp.Models;
using ProductSelectionWebApp.Utility;

namespace ProductSelectionWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly HostingEnvironment _hostingEnvironment;

        [BindProperty]
        public ProductViewModel ProductVM { get; set; }

        public ProductController(ApplicationDbContext db, HostingEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;

            ProductVM = new ProductViewModel
            {
                Product = new Models.Product(),
                ProductList =_db.Product.ToList(),
                ProductCategories=_db.ProductCategory.ToList(),
                InclusionTypes=_db.InclusionType.ToList(),
                Brands=_db.Brand.ToList(),
                Ranges=_db.Range.ToList(),               
              
               
            };

        }
        // GET: Admin/Products
        public async Task<IActionResult> Index()
        {
            var products = await _db.Product.Include(p => p.Brand).Include(p => p.InclusionType).Include(p => p.ProductCategory).Include(m=>m.Range).ToListAsync();
            return View( products);
        }

        // Get: Product / Create
        public IActionResult Create()
        {
            return View(ProductVM);
        }

        // Post: Product / Create
        [HttpPost]
        [ActionName("Create")]
        [ValidateAntiForgeryToken]       
        public async Task<IActionResult> CreatePost()
        {
            if (!ModelState.IsValid)
            {
                return View(ProductVM);
            }

            _db.Product.Add(ProductVM.Product);
            await _db.SaveChangesAsync();

            // Image Being Saves

            string webRootPath = _hostingEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            var ProductFromDb = _db.Product.Find(ProductVM.Product.Id);

            if (files.Count != 0)
            {
                // Image has been uploaded
                var uploads = Path.Combine(webRootPath, StaticDetails.ProductImage);
                var extension = Path.GetExtension(files[0].FileName);

                using (var filestream = new FileStream(Path.Combine(uploads, ProductVM.Product.Id + extension), FileMode.Create))
                {
                    files[0].CopyTo(filestream);
                }

                ProductFromDb.Image = @"\" + StaticDetails.ProductImage + @"\" + ProductVM.Product.Id + extension;

            }
            else
            {
                // When user does not upload image
                var uploads = Path.Combine(webRootPath, StaticDetails.ProductImage + @"\" + StaticDetails.DefaultProductImage);
                System.IO.File.Copy(uploads, webRootPath + @"\" + StaticDetails.CategoryImage + @"\" + ProductVM.ProductCategory.Id + ".jpg");
                ProductFromDb.Image = @"\" + StaticDetails.ProductImage + @"\" + ProductVM.Product.Id + ".jpg";


            }
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        // GET: Temp/Products/Edit/5    
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _db.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["BrandId"] = new SelectList(_db.Brand, "Id", "Name", product.BrandId);
            ViewData["InclusionTypeId"] = new SelectList(_db.InclusionType, "Id", "Name", product.InclusionTypeId);
            ViewData["ProductCategoryId"] = new SelectList(_db.ProductCategory, "Id", "Name", product.ProductCategoryId);
            return View(product);
        }

        // POST: Temp/Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]   
        public async Task<IActionResult> Edit(int id, [Bind("Id,ModelName,ModelNumber,Range,Image,ProductCategoryId,BrandId,InclusionTypeId")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(product);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandId"] = new SelectList(_db.Brand, "Id", "Name", product.BrandId);
            ViewData["InclusionTypeId"] = new SelectList(_db.InclusionType, "Id", "Name", product.InclusionTypeId);
            ViewData["ProductCategoryId"] = new SelectList(_db.ProductCategory, "Id", "Name", product.ProductCategoryId);
            return View(product);
        }


        // GET: Temp/Products/Delete/5      
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _db.Product
                .Include(p => p.Brand)
                .Include(p => p.InclusionType)
                .Include(p => p.ProductCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Temp/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]      
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _db.Product.FindAsync(id);
            _db.Product.Remove(product);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _db.Product.Any(e => e.Id == id);
        }


    }
        }

ProductSelectionWebApp/Areas/Temp/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProductSelectionWebApp.Data;
using ProductSelectionWebApp.Models;

namespace ProductSelectionWebApp.Areas.Temp.Controllers
{
    [Area("Temp")]
    public class BrandsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BrandsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Temp/Brands
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brand.ToListAsync());
        }

        // GET: Temp/Brands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brand
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // GET: Temp/Brands/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Temp/Brands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Url")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Temp/Brands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brand.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // POST: Temp/Brands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Url")] Brand brand)
        {
            if (id != brand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Temp/Brands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brand
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Temp/Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brand = await _context.Brand.FindAsync(id);
            _context.Brand.Remove(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(int id)
        {
            return _context.Brand.Any(e => e.Id == id);
        }
    }
}

ProductSelectionWebApp/Areas/Temp/Controllers/RangesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProductSelectionWebApp.Data;
using ProductSelectionWebApp.Models;

namespace ProductSelectionWebApp.Areas.Temp.Controllers
{
    [Area("Temp")]
    public class RangesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RangesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Temp/Ranges
        public async Task<IActionResult> Index()
        {
            return View(await _context.Range.ToListAsync());
        }

        // GET: Temp/Ranges/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var range = await _context.Range
                .FirstOrDefaultAsync(m => m.Id == id);
            if (range == null)
            {
                return NotFound();
            }

            return View(range);
        }

        // GET: Temp/Ranges/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Temp/Ranges/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Range range)
        {
            if (ModelState.IsValid)
            {
                _context.Add(range);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(range);
        }

        // GET: Temp/Ranges/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var range = await _context.Range.FindAsync(id);
            if (range == null)
            {
                return NotFound();
            }
            return View(range);
        }

        // POST: Temp/Ranges/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Range range)
        {
            if (id != range.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(range);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RangeExists(range.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(range);
        }

        // GET: Temp/Ranges/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var range = await _context.Range
                .FirstOrDefaultAsync(m => m.Id == id);
            if (range == null)
            {
                return NotFound();
            }

            return View(range);
        }

        // POST: Temp/Ranges/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var range = await _context.Range.FindAsync(id);
            _context.Range.Remove(range);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RangeExists(int id)
        {
            return _context.Range.Any(e => e.Id == id);
        }
    }
}

ProductSelectionWebApp/Areas/Admin/Views/Shared/_CategoryIndexPartialView.cshtml
@model IEnumerable<Product>

@if (Model.Count() > 0)
{
    foreach (var item in Model)
    {
        <div class=" card d-inline-block d-inline-flex " style="width:10rem">
            <h6 class="card-header" style="font-size:15px"> @item.ModelName</h6>
            <br />
            <div class="">
                <img src="@item.Image" style="height:100%; width:100%" />
            </div>
            <div class="card-footer">
                <label>@item.Brand</label>
                <label>@item.Range</label>
            </div>
        </div>
    }
}

ProductSelectionWebApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Marvel Home</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Marvel Homes Selection - Admin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="admin" asp-controller="ProductCategory" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="admin" asp-controller="Product" asp-action="Create">Add Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="admin" asp-controller="ProductCategory" asp-action="Create">Add Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="temp" asp-controller="BuildingAreas" asp-action="Create">Add Area</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="temp" asp-controller="Brands" asp-action="Create">Add Brands</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="temp" asp-controller="Ranges" asp-action="Create">Add Range</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Marvel Homes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ProductSelectionWebApp/Areas/Admin/Views/Shared/_ProductCategoryPartialView.cshtml
@model IEnumerable<ProductCategory>

@if (Model.Count() > 0)
{
    foreach (var item in Model)
    {
<div class=" card d-inline-block d-inline-flex " style="width:10rem">
    <h6 class="card-header" style="font-size:15px"> @item.Name</h6>
    <br />
    <div class="">
        <img src="@item.Image" style="height:100%; width:100%" />
    </div>
    <div class="card-footer">

    </div>
</div>
    }
}